HTML base tag - reverse proxy
industrial-edge/hello-world pull request #12
Opened 2024-07-05 12:19 UTC by Boehmi-TB

2024-07-08 09:33 UTC, EndyCZ commented
I would maybe even link  to official documetation that describes the purpose of base tag. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

2024-08-06 11:42 UTC, Boehmi-TB commented
> I would maybe even link to official documetation that describes the purpose of base tag. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

Added with commit https://github.com/industrial-edge/hello-world/pull/12/commits/a20053c5f26f4b9561e740aef7c73f8650f966ca

2024-08-13 11:42 UTC, EndyCZ requested changes
sorry

2024-08-23 10:34 UTC, Boehmi-TB commented on docs/implementation.md
> +  Rewrite Target: /
added in link to docu in [95334fa](https://github.com/industrial-edge/hello-world/pull/12/commits/95334fae6d5f443ee4398a437e43d512a8249673)

2024-08-23 10:35 UTC, Boehmi-TB commented on docs/installation.md
> +
added output in [b17193b](https://github.com/industrial-edge/hello-world/pull/12/commits/b17193b09467d453c9700c7eb9e8810ec2873f6f)

2024-08-23 10:35 UTC, Boehmi-TB commented on docs/installation.md
> +sudo docker run --privileged --rm tonistiigi/binfmt -- install arm64
fixed command in [b17193b](https://github.com/industrial-edge/hello-world/pull/12/commits/b17193b09467d453c9700c7eb9e8810ec2873f6f)

2024-08-23 10:36 UTC, Boehmi-TB commented on docs/installation.md
> +- `docker inspect " Image name"` can be used to check for the image
Solution is to have two docker-compose, one for amd64 one for arm64

2024-09-02 07:31 UTC, EndyCZ commented on docs/installation.md
> +- `docker inspect " Image name"` can be used to check for the image
ah, simple solution. What about if we then add a a file called docker-compose.arm64.yaml for this purpose?

2024-09-06 07:52 UTC, Boehmi-TB commented on docs/installation.md
> +- `docker inspect " Image name"` can be used to check for the image
@EndyCZ 
[a1dc2fe](https://github.com/industrial-edge/hello-world/pull/12/commits/a1dc2fee76dea1275547b59dabee43710d448836) added docker compose for arm64 and updated documentation accordingly

2024-09-06 13:02 UTC, EndyCZ approved these changes
Looks goood.

2024-09-17 11:46 UTC, merged